export const LEVEL_TABLE = [
  {
    key: "lv1",
    max: 150,
    name: "初歩オタ",
    levelClass: "level-1",
    names: { ja: "初歩オタ", en: "Rookie Ota", ko: "초보 오타" },
  },
  {
    key: "lv2",
    max: 200,
    name: "ぽんこつオタ",
    levelClass: "level-1",
    names: { ja: "ぽんこつオタ", en: "Clumsy Ota", ko: "폰코츠 오타" },
  },
  {
    key: "lv3",
    max: 250,
    name: "見習いオタ",
    levelClass: "level-1",
    names: { ja: "見習いオタ", en: "Apprentice Ota", ko: "견습 오타" },
  },
  {
    key: "lv4",
    max: 300,
    name: "修行オタ",
    levelClass: "level-1",
    names: { ja: "修行オタ", en: "Training Ota", ko: "수련 오타" },
  },
  {
    key: "lv5",
    max: 330,
    name: "最前オタ",
    levelClass: "level-2",
    names: { ja: "最前オタ", en: "Front-Row Ota", ko: "최전열 오타" },
  },
  {
    key: "lv6",
    max: 360,
    name: "常連オタ",
    levelClass: "level-2",
    names: { ja: "常連オタ", en: "Regular Ota", ko: "단골 오타" },
  },
  {
    key: "lv7",
    max: 400,
    name: "フロアの要オタ",
    levelClass: "level-2",
    names: { ja: "フロアの要オタ", en: "Floor Anchor Ota", ko: "플로어의 핵심 오타" },
  },
  {
    key: "lv8",
    max: 420,
    name: "ベテランオタ",
    levelClass: "level-2",
    names: { ja: "ベテランオタ", en: "Veteran Ota", ko: "베테랑 오타" },
  },
  {
    key: "lv9",
    max: 450,
    name: "熟練オタ",
    levelClass: "level-2",
    names: { ja: "熟練オタ", en: "Skilled Ota", ko: "숙련 오타" },
  },
  {
    key: "lv10",
    max: 470,
    name: "尊いオタ",
    levelClass: "level-2",
    names: { ja: "尊いオタ", en: "Blessed Ota", ko: "귀한 오타" },
  },
  {
    key: "lv11",
    max: 490,
    name: "爆レスオタ",
    levelClass: "level-2",
    names: { ja: "爆レスオタ", en: "Burst Ota", ko: "폭레스 오타" },
  },
  {
    key: "lv12",
    max: 500,
    name: "伝説のオタ",
    levelClass: "level-2",
    names: { ja: "伝説のオタ", en: "Legendary Ota", ko: "전설의 오타" },
  },
  {
    key: "lv13",
    max: 530,
    name: "異次元オタ",
    levelClass: "level-3",
    names: { ja: "異次元オタ", en: "Otherworld Ota", ko: "이차원 오타" },
  },
  {
    key: "lv14",
    max: 560,
    name: "限界突破オタ",
    levelClass: "level-3",
    names: { ja: "限界突破オタ", en: "Limit Break Ota", ko: "한계돌파 오타" },
  },
  {
    key: "lv15",
    max: 599,
    name: "天界オタ",
    levelClass: "level-3",
    names: { ja: "天界オタ", en: "Celestial Ota", ko: "천계 오타" },
  },
  {
    key: "lv16",
    max: Infinity,
    name: "オタクの神",
    levelClass: "level-3",
    names: { ja: "オタクの神", en: "God of Ota", ko: "오타쿠의 신" },
  },
];



