export const LEVEL_TABLE = [
  {
    key: "lv1",
    max: 100,
    name: "初心オタク",
    levelClass: "level-1",
    names: { ja: "初心オタク", en: "Rookie Ota", ko: "초심 오타쿠" },
  },
  {
    key: "lv2",
    max: 130,
    name: "にわかオタク",
    levelClass: "level-1",
    names: { ja: "にわかオタク", en: "Casual Ota", ko: "니와카 오타쿠" },
  },
  {
    key: "lv3",
    max: 160,
    name: "ぽんこつオタク",
    levelClass: "level-1",
    names: { ja: "ぽんこつオタク", en: "Clumsy Ota", ko: "폰코츠 오타쿠" },
  },
  {
    key: "lv4",
    max: 190,
    name: "修行中オタク",
    levelClass: "level-1",
    names: { ja: "修行中オタク", en: "Training Ota", ko: "수련 중 오타쿠" },
  },
  {
    key: "lv5",
    max: 220,
    name: "最前オタク",
    levelClass: "level-1",
    names: { ja: "最前オタク", en: "Front-Row Ota", ko: "최전열 오타쿠" },
  },
  {
    key: "lv6",
    max: 250,
    name: "安定オタク",
    levelClass: "level-2",
    names: { ja: "安定オタク", en: "Steady Ota", ko: "안정 오타쿠" },
  },
  {
    key: "lv7",
    max: 280,
    name: "フロアの要オタク",
    levelClass: "level-2",
    names: { ja: "フロアの要オタク", en: "Floor Anchor Ota", ko: "플로어 핵심 오타쿠" },
  },
  {
    key: "lv8",
    max: 310,
    name: "ベテランオタク",
    levelClass: "level-2",
    names: { ja: "ベテランオタク", en: "Veteran Ota", ko: "베테랑 오타쿠" },
  },
  {
    key: "lv9",
    max: 340,
    name: "熟練オタク",
    levelClass: "level-2",
    names: { ja: "熟練オタク", en: "Skilled Ota", ko: "숙련 오타쿠" },
  },
  {
    key: "lv10",
    max: 370,
    name: "尊いオタク",
    levelClass: "level-2",
    names: { ja: "尊いオタク", en: "Blessed Ota", ko: "토토이 오タ쿠" },
  },
  {
    key: "lv11",
    max: 400,
    name: "爆レスオタク",
    levelClass: "level-2",
    names: { ja: "爆レスオタク", en: "Burst Response Ota", ko: "폭발 레스 오타쿠" },
  },
  {
    key: "lv12",
    max: 430,
    name: "伝説のオタク",
    levelClass: "level-2",
    names: { ja: "伝説のオタク", en: "Legendary Ota", ko: "전설의 오타쿠" },
  },
  {
    key: "lv13",
    max: 460,
    name: "異次元オタク",
    levelClass: "level-2",
    names: { ja: "異次元オタク", en: "Otherworldly Ota", ko: "이차원 오타쿠" },
  },
  {
    key: "lv14",
    max: 499,
    name: "神オタク",
    levelClass: "level-2",
    names: { ja: "神オタク", en: "Godly Ota", ko: "신 오タ쿠" },
  },
  {
    key: "lv15",
    max: Infinity,
    name: "天界オタク",
    levelClass: "level-3",
    names: { ja: "天界オタク", en: "Celestial Ota", ko: "천계 오타쿠" },
  },
];



